name: test

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_TOKEN: TEST

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Start Vault
        run: docker-compose up -d vault

      - name: testacc
        run: make testacc
